### ISSUE TITLE
Climate link

### ISSUE THREAD

**Issue by jere19** [Vost3/hass-palazzetti#2]
Hello,
I just received my connexionbox and first of all I want to thank you for the integration !
I also tried to link with a climate entity and it just works!
You need to set up a generic thermostat with the switch and whatever temperature sensor you may have (I used the average of the half dozen xiaomi bluetooth sensors i have in my house). 
Here's the config:
```
climate:
  - platform: generic_thermostat
    name: PoeleMaison 
    heater: switch.stove_status
    target_sensor: sensor.TemperatureInterieure
    hot_tolerance: 1.0
    cold_tolerance: 0.5
    min_temp: 17
    max_temp: 22
    ac_mode: false
    min_cycle_duration:
        minutes: 30
```

I'll try to make a pull request soon to enhance a bit the documentation, I'm still struggling to understand some parts :)

I'm impressed at the sensors/counters palazzetti exposes (all temperatures, cumulative pellet usage, etc.). It would be nice to expose some of them as proper sensors.
