### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by tanc** [Vost3/hass-palazzetti#5]
First I want to thank you for taking the time to put this together, I was really happy to discover this integration.

I'm struggling to understand the documentation though, probably because I'm a beginner with Home Assistant.

In your docs there are the following headings, each with yaml to be added somewhere:

Configuration `configuration.yaml`
Service
Automation `automation.yaml`
Sensor
Template
Script

It's not at all clear to me where to put the yaml in each section. It looks like Configuration and Service go together and Automation, Sensor, Template and Script go together but I don't think that is the case.

In my home assistant set up I have the following includes:

```
group: !include groups.yaml
light: !include lights.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
```

In my main `configuration.yaml` I put sensors and switches as well as more global config. Given this set up can you tell me where each of the sections of yaml goes?

**Comment by tanc** [comment]
I've just had a breakthrough ;-) It turns out I was confusing myself by overwriting the top level `sensor` yaml key further down my `configuration.yaml` file. So instead of having one `sensor` key I had two, the second one overriding the first, likewise with the `switch` key. I can now see both the switch and the sensor and can control the power level with a slider, which I can confirm works with my Palazzetti Ginger Idra 15 stove.

I will try to provide a PR with some clarification to the docs, once I'm sure I've got everything set up.

**Comment by tanc** [comment]
The only thing I'm confused about now is the purpose of `input_text.text_test` which is used in `Check pwr state` automation. I got it working by adding an `input_text` key like this in my `configuration.yaml`:

```
input_text:
  text_test:
    name: Power
```

This appears to be only for visual output of the power level in a card and not used elsewhere. Can you confirm its purpose?

One change I made which might be useful is to the `stove_fire_lvl`. Due to the `initial_value` being set to `1` on the `stove_fire_lvl`, when restarting home assistant the wrong power level in my slider was being displayed, always 1. So I updated my `Check pwr state` automation to also set that value:

```
- id: '1'
  alias: Check pwr state
  trigger:
    platform: state
    entity_id: palazzetti.stove
  action:
  - service: input_text.set_value    
    data_template:
      entity_id: input_text.text_test # don't miss to create a input_text "text_test" for test this script
      value: "{{ state_attr('palazzetti.stove', 'PWR') }}"
  - service: input_number.set_value
    data:
      entity_id: input_number.stove_fire_lvl
      value: "{{ states('palazzetti.pwr') }}"
```
